#!/bin/sh -v

# ./compile

cd ./Client
javac userInterface.java Client.java
../bin/server &
java userInterface > data
cat data | ../bin/encryptor | java Client 10000 send
java Client 10001 receive | ../bin/decryptor
